# Generated by Django 4.0.6 on 2022-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_course_options_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id_school',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type_of_education',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
