# Generated by Django 4.0.6 on 2022-07-10 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_employee_id_position_employee_salary_employee_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_position',
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.position'),
        ),
    ]
