# Generated by Django 4.0.6 on 2022-07-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('employee_app', '0003_remove_employee_id_position_employee_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'duration', 'description')},
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.school'),
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_app.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'school', 'description')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='position',
            name='id_department',
        ),
        migrations.RemoveField(
            model_name='position',
            name='permission',
        ),
    ]
