# Generated by Django 4.0.6 on 2022-07-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='school',
        ),
    ]
