# Generated by Django 4.0.6 on 2022-07-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
