# Generated by Django 4.0.6 on 2022-07-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('first_name', 'last_name', 'date_of_birth', 'phone_number', 'email')},
        ),
    ]
